In [2]:
%load_ext autoreload
%autoreload 2

import __confing
__confing.change_to_root_folder()

In [1]:
import pandas as pd
import numpy as np

from src import evaluation 
from src import feature_selection
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler

In [2]:
df=pd.read_sas(r'data\short\H_MHAS_EOL_b.sas7bdat')
df_norm = pd.DataFrame()

In [5]:
df

,codent01,codent03,ps3,ent2,np,unhhidnp,rahhidnp,tipent_01,tipent_03,tipent_12,...,raxrpfcarehrm,rawitwill_m,rawitwill,rawillsp,rawillcg,rawillot,radexpense,radexpensef,rainscovr,raeoldcsnm_m
0,1.0,1.0,1.0,1.0,10.0,110.0,b'110',12.0,12.0,1.0,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,2.0,2.0,2.0,2.0,20.0,220.0,b'220',12.0,11.0,3.0,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,1.0,1.0,1.0,1.0,10.0,410.0,b'410',12.0,12.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0
3,1.0,1.0,1.0,1.0,10.0,710.0,b'710',22.0,21.0,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,16713.091797,1.0,0.0,3.0
4,1.0,1.0,1.0,1.0,10.0,910.0,b'910',11.0,11.0,1.0,...,NaN,0.0,0.0,NaN,NaN,NaN,24429.966797,1.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5618,NaN,NaN,NaN,NaN,20.0,1505220.0,b'1505220',NaN,NaN,4.0,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0
5619,NaN,NaN,NaN,NaN,20.0,1505320.0,b'1505320',NaN,NaN,4.0,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,2.0
5620,NaN,NaN,NaN,NaN,10.0,1507210.0,b'1507210',NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,13056.835938,5.0,NaN,1.0
5621,NaN,NaN,NaN,NaN,20.0,1507220.0,b'1507220',NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3840.245850,5.0,NaN,3.0
5622,NaN,NaN,NaN,NaN,10.0,1510410.0,b'1510410',NaN,NaN,2.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,2.0

In [5]:
columnas_totales = df.columns.tolist()

columnas_elegibles = []

for columna in columnas_totales:
    if 'age' in columna:
        columnas_elegibles.append(columna)

print(columnas_elegibles)

['radage', 'radagef']

In [7]:
def robust_scaler(df,x):
    scaler = RobustScaler()
    return scaler.fit_transform(df[[x]])

In [19]:
def fill_column(df, x, strategy='most_frequent'):
    imputer = SimpleImputer(strategy=strategy)
    print(df[x].value_counts())
    print(f'nulls: {df[x].isnull().sum()}')
    df[[x]] = imputer.fit_transform(df[[x]])  # Modificar esta línea
    return df[x]

# Ayudas

## ayuda formal e informal

In [29]:
formal = 'raxricaany'
df_norm[formal]=fill_column(df=df,x=formal)

raxricaany
1.0    3568
0.0    1969
Name: count, dtype: int64
nulls: 86

In [30]:
informal = 'raxracaany'
df_norm[informal]=fill_column(df,informal)

raxracaany
1.0    3312
0.0    2272
Name: count, dtype: int64
nulls: 39

## ayuda del gobierno

In [ ]:
gobierno='raxhigov'
df[gobierno]=fill_column(df,gobierno)

raxhigov
1.0    4651
0.0     925
Name: count, dtype: int64
nulls: 47

## NO hay columnas HLP en el dataset b

## NO hay columnas smoke en el dataset b

# Comportamiento

In [ ]:
angry='raoangry'
df[angry]=fill_column(df,angry)

raoangry
3.0    3573
2.0    1208
1.0     812
Name: count, dtype: int64
nulls: 30

`de la encuesta solo está el humor`